### ISSUE TITLE
Blazor Web App - IIS - App shutdown on refresh - HTTP Error 503.0 - Server has been shutdown

### ISSUE THREAD

**Issue by kuldeepcis-lab** [dotnet/blazor-samples#348] opened 2024-09-05 07:34 UTC
**Describe the issue**

I'm using the .NET 8 Blazor web app template, which includes both a client and server project. In the server project, I have an API controller that I call using `HttpClient`. When running the application on Kestrel (using commands like `dotnet run` or `dotnet projectassembly.dll`), everything works as expected. However, when I deploy the application to either a local or remote IIS, or run it via Visual Studio on IIS, the site starts but fails after requesting the Web API controllers. It returns a 503 error for all requests, and the application becomes unresponsive with no indication of what went wrong.

**To Reproduce**

1. Go to repository and clone [BlazorWebappOidc](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorWebAppOidc) and Open the application in Visual Studio.
2. Add an IIS Settings to launchsettings.json to run the application on IIS locally then Run

` "iisSettings": { "windowsAuthentication": false, "anonymousAuthentication": true, "iisExpress": { "applicationUrl": "http://localhost:46294", "sslPort": 44381 }  },"profiles": {   "IIS Express": { "commandName": "IISExpress", "launchBrowser": true, "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}", "environmentVariables": { "ASPNETCORE_ENVIRONMENT": "Development" }   } }`

3.  Add an API controller to server project and add a couple of method to get data from database.
4.  Register HTTPClient at client side project to call the API.
5. lets run the project on the IIS profile and try to fetch data via method we have added into API controller  this will return response Error 503 Shut down or just refresh the page it will show the error.

**Expected behavior**

Application should work smoothly and get data from database on API calls and don't shut down on refresh or Api calling.

**Screenshots**
![Screenshot_15](https://github.com/user-attachments/assets/50f6fe33-d5f7-40ee-8d50-52b39b529f6a)
![Screenshot_16](https://github.com/user-attachments/assets/e325aeb7-c318-4291-9f7b-09f48e6a2ec1)
---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Expected behavior**

**Comment by guardrex** [comment] 2024-09-05 11:08
I'm not sure if this is the same or different than your issue at https://github.com/dotnet/aspnetcore/issues/57545, but whatever the problem is, it must be resolved by the product unit.

If it's a different error than https://github.com/dotnet/aspnetcore/issues/57545, then open a new issue (and you can mention the existing issue in it). If it's the same issue, then add a comment on this to https://github.com/dotnet/aspnetcore/issues/57545.

If you open a new issue, then please add the following line to your opening comment so that I can follow along for possible article updates ...

```
cc: @guardrex https://github.com/dotnet/blazor-samples/issues/348
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

If you place a comment on the existing issue, no worries on that ... I'm already 👂 on that one.

**Closed by guardrex** 2024-09-05 11:08 UTC
Labels: Not triaged

**Comment by kuldeepcis-lab** [comment] 2024-09-05 12:00
Hi @guardrex 
This is **not** the same issue it is **different** from the previous one.
**By Reducing the size of claim worked and solved the too-long request** [problem](https://github.com/dotnet/aspnetcore/issues/57545) I am successfully authenticated and after a successful callback, I was redirected to the Blazor web app. 
But Now in this app when I refresh it or Call an API Controller exists in the Blazor web app Server part It always returns **503 - Service not available / server has been Shut down,** without any Exception or Indication what went wrong.

**Comment by guardrex** [comment] 2024-09-05 12:02
Gotcha ... then open a new issue for them and please CC: me on it.

**Comment by kuldeepcis-lab** [comment] 2024-09-05 12:06
Okay 👍
