### ISSUE TITLE
SignalR in BlazorWebAppOidcBff

### ISSUE THREAD

**Issue by georgait** [dotnet/blazor-samples#221] opened 2024-03-01 17:06 UTC
**Describe the issue**
I use the `BlazorWebAppOidcBff` as template. 

In short i have in the minimalApi a notification hub (signalr hub) and i want to consume the notifications from the `BlazorWebAppOidc.Client` project. 

This is what i've tried so far:
```
//BlazorWebAppOidc project:
app.MapForwarder("/notificationhub/{**catch-all}", "https://localhost:7188", transformer =>
{
    transformer.AddRequestTransform(async transformContext =>
    {
       // add access_token to uri as query parameter
        var accessToken = await transformContext.HttpContext.GetAccessTokenAsync();
        var request = transformContext.HttpContext.Request;
        var url = transformContext.DestinationPrefix + request.Path.Value + request.QueryString.Value + $"&access_token={accessToken}";
        var uriBuilder = new UriBuilder(url);
        transformContext.ProxyRequest.RequestUri = uriBuilder.Uri;
    });
}).RequireAuthorization();
```

```
// BlazorWebAppOidc.Client project
// Component 
`@rendermode InteractiveAuto`
protected override async Task OnInitializedAsync()
{
    _hubConnection = new HubConnectionBuilder()            
        .WithUrl("https://localhost:7129/notificationhub")  // blazor webapp host, it should be transformed into the minimal api's host via yarp in the MapForwarder method
        .Build();
    _hubConnection.On<string>("ReceiveNotification", HandleMessage);
    await _hubConnection.StartAsync();
}
```
```
// minimalApi project
// Service registration
services.AddAuthentication("Bearer")
     .AddJwtBearer("Bearer", options =>
     {
         options.Authority = configuration["identityServer:authority"];

         options.TokenValidationParameters = new TokenValidationParameters
         {
             ValidateAudience = false
         };

         options.Events = new JwtBearerEvents
         {
             OnMessageReceived = context =>
             {
                 var accessToken = context.Request.Query["access_token"];

                 // If the request is for our hub
                 var path = context.HttpContext.Request.Path;
                 if (!string.IsNullOrEmpty(accessToken) &&
                     (path.StartsWithSegments("/notificationhub")))
                 {
                     // Read the token out of the query string
                     context.Token = accessToken;
                 }
                 return Task.CompletedTask;
             }
         };
     });
 // Application Pipeline
 app.MapHub<NotificationHub>("/notificationHub").RequireAuthorization(AuthorizationPolicies.ApiScope);
```

I tried this approach after reading the [docs ](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0) about signalr authentication.

With this setup the first time the component renders everything works as expected but if i refresh the page i get this error:

> 
> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader)
>    at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)

First of all Is this approach optimal or i am doing something wrong? In general what is the best approach for handling signalr authentication when the hub is located in the remote api and we use the bff pattern?

**.NET Version**
.NET 8

---
#### Issue Details

⚠ *Do not edit this section. It is required for issue processing.*

* Content Source: [dotnet/blazor-samples](https://github.com/dotnet/blazor-samples)
* GitHub Login: @guardrex

**Comment by guardrex** [comment] 2024-03-01 17:11
Duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/31899.

See the PU issue for details on this ... 

https://github.com/dotnet/aspnetcore/issues/54134#issuecomment-1967290030

**Closed by guardrex** 2024-03-01 17:11 UTC
Labels: Not triaged

**Comment by georgait** [comment] 2024-03-01 17:20
thanks for the reply, the approach i shared above does follow the best securty practices or is there any other way of handling authentication in this example?
